---
- hosts: linux
  gather_facts: no
  become: yes

  tasks:
    - name: install nginx
      package:
        name:
          - nginx
        state: latest

    - name: copy index.html
      copy:
        src: /ansible/ansible/playbooks/files/index.html
        dest: /usr/share/nginx/html/index.html

    - name: start nginx
      service:
        name: nginx
        enabled: yes
        state: started
